backend:
  name: github
  repo: codechef93/eth-vc
  branch: main
  
media_folder: content/images/
public_folder: ../images/
  
collections:
  - name: blogs
    label: Blogs
    folder: "content/blogs"
    identifier_field: "name"
    extension: "json"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }